#
FROM postgres:latest
MAINTAINER Jekshmek <yaroshjeka@gmail.com>
# RUN groupadd -r postgres --gid=999 && useradd -r -g postgres --uid=999 postgres
#ENV PGDATA /var/lib/postgresql/data
#RUN mkdir -p "$PGDATA" && chown -R postgres:postgres "$PGDATA" && chmod 777 "$PGDATA" 
# VOLUME /var/lib/postgresql/data 
 # chown -R postgres:postgres /var/lib/postgresql/data
# sudo docker run -it --rm --user postgres:postgres postgres
